name: Iris Feature Pipeline Daily

on:
    push:
    schedule:
        - cron: '0 3 * * *'

jobs:
    iris-feature-pipeline-daily:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Cache conda
              uses: actions/cache@v3
              env:
                    # Increase this value to reset cache if etc/example-environment.yml has not changed
                    CACHE_NUMBER: 0
              with:
                path: ~/conda_pkgs_dir
                key:
                    ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
                    hashFiles('environment.yml') }}
            - uses: conda-incubator/setup-miniconda@v2
              with:
                activate-environment: id2223
                environment-file: environment.yml
                python-version: 3.10.13
                auto-activate-base: false
                use-only-tar-bz2: true # This needs to be set for caching to work properly
            - name: Run pipeline
              run: |
                python Task_1/iris-feature-pipeline-daily.py
