name: Python Package using Conda

on: [push, workflow_call]

jobs:
  set-up-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: id2223
        environment-file: environment.yml
        python-version: 3.10.13
        auto-activate-base: false
        use-only-tar-bz2: true # This needs to be set for caching to work properly
    - run: |
        conda info
        conda list
