name: Python Package using Conda

on: [push, workflow_call]

jobs:
  set-up-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: id2223
        environment-file: environment.yml
        python-version: 3.10.13
        auto-activate-base: false
    - run: |
        conda info
        conda list
