name: Wine Batch Inference Pipeline

on:
  workflow_dispatch:
  # schedule:
  #     - cron: "0 15 * * *" # 3pm UTC

env:
    HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}

jobs:
    wine-batch-inference-pipeline:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('Task_2/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-
            - uses: actions/setup-python@v3
              with:
                python-version: '3.10.13'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r Task_2/requirements.txt
            - name: Run pipeline
              run: |
                python Task_2/wine-class-batch-inference-pipeline.py
                